# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pe3_development

test:
  <<: *default
  database: pe3_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

# ⬇⬇⬇ 關鍵：頂層的 cable 設定（SolidCable 會用到）
cable:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
