# config/database.yml
# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pe3_development

test:
  <<: *default
  database: pe3_test

production:
  primary:
    adapter: postgresql
    url: <%= ENV.fetch("DATABASE_URL") %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 3) %>

  queue:
    adapter: postgresql
    url: <%= ENV.fetch("DATABASE_URL") %>

  cache:
    adapter: postgresql
    url: <%= ENV.fetch("DATABASE_URL") %>

  cable:
    adapter: postgresql
    url: <%= ENV.fetch("DATABASE_URL") %>
